package defaults

import (
	"fmt"
	"math"
	"os"
	"strconv"
	"time"
)

type DefaultConfig struct {
	Domain           string
	TTL              int // in sec
	DNSServerAddress string
	DownloadDir      string
	Comment          string

	BunnyBaseURL      string
	BunnyAPIToken     string
	BunnyZoneID       string
	ResponseCacheTime time.Duration // In seconds

	NetworkLayer       NetworkLayer
	CompressionEnabled bool
	// MaxTXTRecordSize is the maximum size of a TXT record
	// For UDP network layer max value is 1000
	// For TCP network layer max value is 4000
	MaxTXTRecordCharacterSize int

	// BatchSize Settings
	DownloadBatchSize int
	UploadBatchSize   int
	StreamBatchSize   int
	DeleteBatchSize   int

	DNSRetryLimit int // For DNS query

	// API Server
	HTTPPort int
}

func NewDefaultConfig() *DefaultConfig {
	domain := getDefaultValue("DOMAIN", "auenkr.qzz.io")

	dnsServerAddress := getDefaultValue("DNS_SERVER_ADDRESS", "1.1.1.1:53")
	downloadDir := getDefaultValue("DOWNLOAD_DIR", ".temp/download")

	bunnyBaseURL := getDefaultValue("BUNNY_BASE_URL", "https://api.bunny.net")
	bunnyAPIToken := getDefaultValue("BUNNY_API_TOKEN", "")
	bunnyZoneID := getDefaultValue("BUNNY_ZONE_ID", "")
	responseCacheTimeTemp, _ := strconv.Atoi(getDefaultValue("BUNNY_RESPONSE_CACHE_TIME", "300"))
	responseCacheTime := time.Duration(responseCacheTimeTemp) * time.Second

	ttl, _ := strconv.Atoi(getDefaultValue("TTL", "3600"))
	comment := getDefaultValue("DEFAULT_COMMENT", "generated by dns-storage")

	compressionEnabled := getDefaultValue("COMPRESSION_ENABLED", "true")

	networkLayer := NetworkLayer(getDefaultValue("NETWORK_LAYER", "tcp"))
	maxTXTRecordCharacterSize, _ := strconv.Atoi(getDefaultValue("MAX_TXT_RECORD_CHARACTER_SIZE", "1000"))

	switch networkLayer {
	case UDPTransportLayer:
		if maxTXTRecordCharacterSize > 1000 {
			panic("max txt record character size for udp is 1000")
		}
	case TCPTransportLayer:
		if maxTXTRecordCharacterSize > 4000 {
			panic("max txt record character size for tcp is 4000")
		}
	default:
		panic("network layer is not supported")
	}

	// BatchSize Settings
	DownloadBatchSize, _ := strconv.Atoi(getDefaultValue("DOWNLOAD_BATCH_SIZE", "1"))
	UploadBatchSize, _ := strconv.Atoi(getDefaultValue("UPLOAD_BATCH_SIZE", "50"))
	DeleteBatchSize, _ := strconv.Atoi(getDefaultValue("DELETE_BATCH_SIZE", "100"))
	StreamBatchSize, _ := strconv.Atoi(getDefaultValue("STREAM_BATCH_SIZE", "30"))

	DNSRetryLimit, _ := strconv.Atoi(getDefaultValue("DNS_RETRY_LIMIT", "8"))

	// API Server
	httpPort, _ := strconv.Atoi(getDefaultValue("HTTP_PORT", "8080"))

	config := &DefaultConfig{
		Domain:           domain,
		TTL:              ttl,
		DNSServerAddress: dnsServerAddress,
		DownloadDir:      downloadDir,
		Comment:          comment,

		BunnyBaseURL:      bunnyBaseURL,
		BunnyAPIToken:     bunnyAPIToken,
		BunnyZoneID:       bunnyZoneID,
		ResponseCacheTime: responseCacheTime,

		NetworkLayer:              networkLayer,
		MaxTXTRecordCharacterSize: 4000,

		CompressionEnabled: compressionEnabled == "true",

		DownloadBatchSize: DownloadBatchSize,
		UploadBatchSize:   UploadBatchSize,
		DeleteBatchSize:   DeleteBatchSize,
		StreamBatchSize:   StreamBatchSize,
		DNSRetryLimit:     DNSRetryLimit,

		HTTPPort: httpPort,
	}

	fmt.Printf("\nConfig:\n%#v\n\n", config)
	return config
}

func getDefaultValue(env string, defaultValue string) string {
	res := os.Getenv(env)
	if res == "" {
		res = defaultValue
	}
	return res
}

type NetworkLayer string

const (
	TCPTransportLayer NetworkLayer = "tcp"
	UDPTransportLayer NetworkLayer = "udp"
)

// GetMaxChunkByteSize returns the maximum byte's size a chunk can be
// Binary bytes uses 8 bits per byte.
// Base64 characters represent 6 bits[ log2(64)=6 ].
func (c *DefaultConfig) GetMaxChunkByteSize() int {
	binaryCharacter := 8.0
	base64Character := 6.0
	ratio := base64Character / binaryCharacter

	maxChunkByteSize := math.Ceil(float64(c.MaxTXTRecordCharacterSize) * ratio)
	return int(maxChunkByteSize)
}
